AWSTemplateFormatVersion: '2010-09-09'
Description:
  Create ElastiCache instance
Metadata:
  # Specify input parameter grouping and ordering
  "AWS::CloudFormation::Interface": 
    ParameterGroups: 
      - Label: 
          default: "Prefix"
        Parameters: 
          - Prefix
Parameters:
  Prefix:
    Description: "Prefix for resource name"
    Type: String
    Default: "FirstPj-" # Prefix for resource name
  MemcachedVersion:
    Type: String
    Default: "1.6.17"
    AllowedValues: [ "1.6.17" ]
  ElastiCacheInstanceClass:
    Type: String
    Default: "cache.t4g.micro" 
  ElastiCacheNodeCount:
    Type: String
    Default: "1"
Resources:
  # ElastiCache instance
  ElastiCacheInstance:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AZMode: single-az
      AutoMinorVersionUpgrade: false
      CacheNodeType: !Ref ElastiCacheInstanceClass
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      ClusterName: !Sub "${Prefix}ElastiCache-Memcached"
      Engine: memcached
      EngineVersion: !Ref MemcachedVersion
      NumCacheNodes: !Ref ElastiCacheNodeCount
      Port: 11211
      PreferredAvailabilityZone: !Select [ 0, !GetAZs '' ]
      PreferredMaintenanceWindow: sun:17:00-sun:18:00
      VpcSecurityGroupIds:
        - !ImportValue MemcachedSecurityGroup
  # ElastiCache Subnet Group
  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: !Sub "${Prefix}ElastiCacheSubnetGroup"
      Description: !Sub "${Prefix}ElastiCache Subnet Group"
      SubnetIds:
        - !ImportValue PrivateSubnet1
  # ElastiCache Parameter Group
  ElastiCacheParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: memcached1.6
      Description: !Sub "${Prefix}Memcached Parameter Group"